### ISSUE TITLE
Use cached questions [$50]

### ISSUE THREAD

**Issue by LemonAndroid** [LemonAndroid/qanda#48]
Could be used: LemonAndroid/qanda-cache `<script to load questions> | <script to "parse" questions>`

Save questions in a database and serve them instead of calculating again all the time.

**Comment by rsercano** [comment]
Hello @LemonAndroid I'm interested in this issue, can you please describe more ?

**Comment by LemonAndroid** [comment]
No

**Comment by LemonAndroid** [comment]
Come up with a first pull request and I'll do a code review.

**Comment by LemonAndroid** [comment]
If you don't know what to do at all, add a new file TODO.md and describe your vague idea of what needs to be done and I'll review that.

**Comment by rsercano** [comment]
Where're your manners ??? So you want me to present an idea, do it, and do "something" without a brief code documentation at all, and treat me like I'm an animal ? What the hell is the answer "No" means, if you can't even describe what's your issue is why the hell do you raise an issue ??? And all those non-sense for only 50$, no thanks!

I'm a developer not your slave, learn how to act first.

**Comment by LemonAndroid** [comment]
@rsercano learn some manners yourself first. I didn't act in any condescending way.

**Comment by LemonAndroid** [comment]
`Hello @LemonAndroid I'm interested in this issue, can you please describe more ?` is just bloat. Add meaningful comments.

**Comment by rsercano** [comment]
I just asked you to add more detail about issue, and look at your answers 
`No` 
`Come up with a first pull request and I'll do a code review.` 
`If you don't know what to do, add a TODO.md and I'll review` (which you've removed)

Do I look like a slave ? You could say there's nothing to be explained (which is wrong in my opinion.)

**Comment by crtmneric** [comment]
@LemonAndroid 

> No

>  I didn't act in any condescending way.

You didnt ? I came here for the bounty and development but it looks like you are trying to punish your slaves for 50 dollar is this how ur wife acts u in bed ?

**Comment by LemonAndroid** [comment]
I don't know why go on about `being treated as a slave`. This is a voluntary bounty, how are you enslaved?

**Comment by LemonAndroid** [comment]
There are hundreds of other bounties on bountysource.com and gitcoin.co, feel very free to do another bounty or no bounty or whatever. you are a free man, you know that, right?

**Comment by crtmneric** [comment]
Let me explain ; If a bounty hunter wants to solve your issue and ask a question like 

> Hello @LemonAndroid I'm interested in this issue, can you please describe more ?

this and u know that he want to help you, you cant just say no and ask for code first. Did u run when u have born ? and he said that he already took a look then ask for " MORE " this means he cant get somethink and ask for a simple describe! U cant even try to be cooperative then ask for people to solve ur issue !

**Comment by LemonAndroid** [comment]
I need some question or starting point to help you get going. Can be as simple as a question or one todo item that you find for this issue.

**Comment by LemonAndroid** [comment]
The idea of this PR is to save the questions to a database and then retrieve them from there. But i need some input from you, to know how to help you.
